# Generated by Django 4.0.6 on 2022-07-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birth_day', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('github', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(max_length=25)),
                ('skill_level', models.IntegerField()),
            ],
        ),
    ]
