# Generated by Django 4.0.6 on 2022-07-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_profile_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transcription',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
