# Generated by Django 4.0.6 on 2022-07-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_profile_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
