# Generated by Django 4.0.6 on 2022-07-16 04:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_category_category_image_alter_post_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transcription',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
    ]
