# Generated by Django 4.0.6 on 2022-07-16 07:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_post_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
