# Generated by Django 4.0.6 on 2022-07-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_alter_profile_picture_alter_profile_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.IntegerField(null=True),
        ),
    ]
